### ISSUE TITLE
Investigating portal issues

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#1010]
Our portal implementation is incomplete, it's basically a proof of concept waiting for more to be done.

Our portal code is very similar to the one in [RBQUAKE-3](https://github.com/RobertBeckebans/RBQUAKE-3), what is believed to be the most recent version of XreaL, so I guess this cannot help us more.

I identified that [Tremulous 1.3 by GrangerHub](https://github.com/GrangerHub/tremulous), which is based on ioquake3, has working portal blending in its `opengl2` renderer.

The code is much complete there. This seems to be nothing more than ioquake3 implementation and we could look at the [ioquake3 impementation](https://github.com/ioquake/ioq3/) as well, but this build makes easier to load tremulous maps to compare with Dæmon.

I noticed we have some very small `portal_fp.glsl` and `portal_vp.glsl` shaders while ioquake3 just use `generic_fp.glsl` and `generic_vp.glsl` for portals.

I noticed that if I tell the Dæmon engine to use `Render_generic` instead of `Render_portal` function (generic GLSL instead of portal GLSL), the portals are rendered the same, and despite blending works on all other textures with `generic` glsl, this still doesn't work with portals.

This seems to confirm our portals are not rendered like other textures, I always assumed that portals were rendered after everything else is done. For sure they render above translucent textures that are in front of them.

Known portal issues:

- https://github.com/DaemonEngine/Daemon/issues/935
- https://github.com/DaemonEngine/Daemon/issues/1005
- https://github.com/DaemonEngine/Daemon/issues/1011
- https://github.com/DaemonEngine/Daemon/issues/1012
- https://github.com/Unvanquished/Unvanquished/issues/2476
- https://github.com/DaemonEngine/Daemon/issues/1021

**Comment by illwieckz** [comment]
`Render_portal()` is not executed at all.

**Comment by illwieckz** [comment]
Even if I make sure it runs that does nothing.

Maybe `Render_portal()` is just used to fade the portal with another texture using `alphaGen portal` and do not render the portal at all.

**Comment by VReaperV** [comment]
> Even if I make sure it runs that does nothing.
> 
> Maybe `Render_portal()` is just used to render the texture that is faded with the portal when using `alphaGen portal` and this function does not render the portal at all.

Could it be in https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/tr_backend.cpp#L5505 and https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/tr_backend.cpp#L5577?

The first seems to be used in depth pre-pass and the second one to actually render the portal.

**Comment by illwieckz** [comment]
Hmm, `PreparePortalCommand` was previously named `R_PreparePortalCmd`, introduced in commit 62c51af982c3120fbe334cb7019f1ef888486ee3 by @gimhael.

The commit is named `Add support for multiple and nested portals by using a stencil mask.`

**Comment by VReaperV** [comment]
> Hmm, `PreparePortalCommand` was previously named `R_PreparePortalCmd`, introduced in commit [62c51af](https://github.com/DaemonEngine/Daemon/commit/62c51af982c3120fbe334cb7019f1ef888486ee3) by @gimhael.
> 
> The commit is named `Add support for multiple and nested portals by using a stencil mask.`

Oh, true, depth is written somewhere between calls to PreparePortalCommand::ExecuteSelf( ) and FinalisePortalCommand::ExecuteSelf( ).

Looks like this https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/tr_main.cpp#L1835 is where the portal rendering functions are called. So the actual portal rendering might be at https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/tr_main.cpp#L1893.

**Comment by VReaperV** [comment]
It looks like both methods add new rendering cmds for the backend to render. It seems to be rendering them in the order they were added, and the only draw call using a texture rendered from a portal seems to be between those 2 cmds. So I think the actual rendering of the portal surface happens somewhere here: https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/tr_main.cpp#L1871-L1895
Might be wrong though.

**Comment by VReaperV** [comment]
> Maybe the portal is written to the wrong framebuffer and written directly on the screen? 🤔️

The framebuffers seem to be correct... At least the drawing of the actual map seems to use the same framebuffer for everything including portals, then a different framebuffer is used for the UI.

**Comment by illwieckz** [comment]
What I mean is that maybe the portal should be rendered to a specific framebuffer to be able to render it?

Or is it simply expected to be rendered first so other stages are blended later on it?

**Comment by VReaperV** [comment]
> What I mean is that maybe the portal should be rendered to a specific framebuffer to be able to render it?
> 
> Or is it simply expected to be rendered first so other stages are blended later on it?

The latter is the case I think. It doesn't seem to be using separate framebuffers, instead it sets the matrices for the shader that renders the portals so that it's rendered as if you were at the other side of the portal itself. And they are indeed rendered first, so probably supposed to blend with stuff on top yeah.

**Comment by illwieckz** [comment]
What can prevent a translucent object in front of a portal to not blend with it?

As seen in:

- https://github.com/DaemonEngine/Daemon/issues/1012

I guess we can get that result if:

- The portal is painted on top of everything,
- The renderer wrongly thinks there is something opaque above the translucent texture.

Is there any other possibility?

**Comment by VReaperV** [comment]
> What can prevent a translucent object in front of a portal to not blend with it?
> 
> As seen in:
> 
> * [Portals render above translucent textures #1012](https://github.com/DaemonEngine/Daemon/issues/1012)
> 
> I guess we can get that result if:
> 
> * The portal is painted on top of everything,
> * The renderer wrongly thinks there is something opaque above the translucent texture.
> 
> Is there any other possibility?

Not sure... Translucent stuff seems to always be rendered last (before the player though), so things that are in front of them get rendered properly because the depth test fails there. It would seem like neither of these are the case with things rendered by portals though. The translucent stuff also seems to be rendered with this shader: https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/glsl_source/generic_fp.glsl. I'm not seeing anything in it that would make it fail, maybe the inputs there should be checked (e. g. by outputting the values from texture samplers directly).

**Comment by VReaperV** [comment]
Actually, look at this:
![unvanquished_2024-01-05_023205_000](https://github.com/DaemonEngine/Daemon/assets/10687142/8d822bca-f47b-4fc5-91fb-59c38547b1b8)
I noclipped into the window (the window has 2 sides), you can see that on the right it's rendered is if I was in the room behind the window, on the left it's rendered as if I was behind the second window pane, but in the middle it appears to blend correctly. The window is being clipped this way because of zNear (`/r_znear 3`, which is the default) and my position.

**Comment by illwieckz** [comment]
Ah yes, I now remember having noticed that in the past but I forgot it.

Here we can see both sides of the window being rendered above the portal, but at some point this disappear:

![unvanquished_2024-01-05_004612_000](https://github.com/DaemonEngine/Daemon/assets/2311649/bce5db4d-46fb-4c4a-85c0-798279f19d0b)

**Comment by illwieckz** [comment]
The geometry of the what the portal renders have an effect on the window:

![unvanquished_2024-01-05_004949_000](https://github.com/DaemonEngine/Daemon/assets/2311649/5044077b-dac2-4b0c-ba51-f9d8a6f83da7)

**Comment by illwieckz** [comment]
![unvanquished_2024-01-05_005142_000](https://github.com/DaemonEngine/Daemon/assets/2311649/b1ec3906-ff07-48ac-8c00-8142b7f9f19d)

![unvanquished_2024-01-05_005225_000](https://github.com/DaemonEngine/Daemon/assets/2311649/b21f5161-ca2d-4fa3-ba33-bd82395a881c)

**Comment by VReaperV** [comment]
This also affects building outlines, here's with z_near 100:
![unvanquished_2024-01-05_025741_000](https://github.com/DaemonEngine/Daemon/assets/10687142/e8c682c0-3db9-409c-87e5-e4f363dd8e0d)

**Comment by VReaperV** [comment]
This also makes me think it might have something to do with depth (perhaps how it's used in `generic_fp.glsl` or the input values there?):

![unvanquished_2024-01-05_031651_000](https://github.com/DaemonEngine/Daemon/assets/10687142/5385e1ae-0c51-4761-b450-ffea07ffd94f)
![unvanquished_2024-01-05_031804_000](https://github.com/DaemonEngine/Daemon/assets/10687142/7f9fc61e-12ee-4985-9d62-5a1fb874cc11)
![unvanquished_2024-01-05_034743_000](https://github.com/DaemonEngine/Daemon/assets/10687142/2b705a8b-0069-4113-8ee8-1a726d92d2d5)

**Comment by VReaperV** [comment]
It's also worth noting that you can't do that on grangermaze:
![unvanquished_2024-01-05_032817_000](https://github.com/DaemonEngine/Daemon/assets/10687142/8b0befee-515d-4335-b0b4-e12263c752a1)
That's probably because the depth there is set to 1.0 since there's nothing behind the portal.

**Comment by VReaperV** [comment]
@illwieckz I believe I found the issue. These are the color buffer and depth buffer as seen in Nsight on pulse near the window:
![debug_a1](https://github.com/DaemonEngine/Daemon/assets/10687142/e839bb0b-3747-467e-98ab-0e004d5a97cc)
![debug_a1d](https://github.com/DaemonEngine/Daemon/assets/10687142/276ce2e1-8a04-4121-abc0-5ecd658c9bd4)
The stuff rendered in portals has z-values around 0-0.5, mostly towards 0.0, but everything else has values close to 1.0.
This is the same place but noclipping into the window:
![debug_a2](https://github.com/DaemonEngine/Daemon/assets/10687142/121cf588-ebaf-447a-977f-d2ae09c4fe97)
![debug_a2d](https://github.com/DaemonEngine/Daemon/assets/10687142/82a296ef-f4fc-4d42-9fd2-9750fa8a465c)
You can see where the values in the depth buffer are different in places that actually got blended.
And this is the same thing with `/r_znear 50`:
![debug_a3](https://github.com/DaemonEngine/Daemon/assets/10687142/b9ae3522-8de1-405a-849d-12ff3c920df4)
![debug_a3d](https://github.com/DaemonEngine/Daemon/assets/10687142/731e0eed-3516-469a-92e1-3c1f36f2d2d4)
This results in more of the depth buffer being populated normally, rather than just values closer to 1.0. The issue is that the depth outputted by the portal rendering is incorrect (well, it may be correct for the portal's "camera", but not for this).

**Comment by illwieckz** [comment]
What can be the fix? multiply/shift the portal depth-from-portal-point-of-view with current surface depth?

**Comment by VReaperV** [comment]
Maybe, although that might introduce issues with depth testing during portal rendering. We can just draw the portal surface again after everything in the portal is rendered, but with ColorMask set to false on all colours, depth test set to GL_ALWAYS and depth write enabled. In fact, the engine appears to be already doing so, but with depth test disabled, which prevents the depth write (from refpages: "GL_DEPTH_TEST
If enabled, do depth comparisons and update the depth buffer. Note that even if the depth buffer exists and the depth mask is non-zero, the depth buffer is not updated if the depth test is disabled. See [glDepthFunc](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDepthFunc.xhtml) and [glDepthRange](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glDepthRange.xhtml).").

Also, it's worth noting that `GL_State` does not take anything other than GL_LEQUAL, GL_LESS, and GL_EQUAL as its values, so that should probably be expanded.

**Comment by VReaperV** [comment]
I think changing this https://github.com/DaemonEngine/Daemon/blob/6d1441070ebc8d3faa775754c201cdc95079c578/src/engine/renderer/tr_backend.cpp#L5609 to `GL_State( GLS_DEPTHMASK_TRUE | GLS_DEPTHTEST_ENABLE | GLS_COLORMASK_BITS );` should fix it.

**Comment by VReaperV** [comment]
#1005 and #1021 will be partially fixed by #1031, full fix in a later pr.

**Comment by VReaperV** [comment]
Last remaining issue fixed in https://github.com/DaemonEngine/Daemon/pull/1022.
