### ISSUE TITLE
x86 WebP DLL wrongly assumes stack alignment

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#145]
The libwebp-5.dll shipped in the msvc32-4 external_deps seems to be actually incompatible with MSVC. On the x86 Windows platform, only 4-byte stack alignment is guaranteed. But the code in this DLL apparently assumes that the stack will be 16-byte aligned when using SSE instructions on stack argument (causing it to crash).

I tried to find a compile switch or attribute to force 16-byte stack alignment, but no luck.

Where does this code come from anyway? Is it built by us or from a binary release?

**Comment by DolceTriade** [comment]
It's built by us using https://github.com/DaemonEngine/Daemon/blob/master/external_deps/build.sh

**Comment by slipher** [comment]
#151 should make the external_deps build script build compatible DLLs, so the issue will be fixed whenever a new version of the external_deps is released.

**Comment by illwieckz** [comment]
is this issue fixed?

**Comment by slipher** [comment]
No, last external_deps release was in 2015.

**Comment by slipher** [comment]
Fixed by #401.

**Comment by DolceTriade** [comment]
Can we remove webp support? We have moved to crn for all assets. For all other assets, just use png instead of webp.

**Comment by slipher** [comment]
IIRC the idea was to use webp for lossless images. But yeah, maybe the advantage of webp over png there isn't enough to justify having the library.

**Comment by illwieckz** [comment]
We make use of WebP and there are strong reasons for it. Neither CRN, JPEG or PNG can replace it properly.

Skyboxes don't work in `.crn` for some reasons and JPEG is not an option: lossy WebP has far superior quality than JPEG, especially on starry-night scenes like Ingar's space skyboxes (`tex-space` package). Those files are just the worst nightmare of JPEG, pushing JPEG to produce the worst it can do.

I did [a comparison](https://unvanquished.net/a-tremulous-deja-vu-feeling/) in 2015 (wow, time passes!) and the results are eloquent:

[![wasteland](https://unvanquished.net/wp-content/uploads/2015/08/wasteland.webp-jpg-comparison1.png)](https://unvanquished.net/wp-content/uploads/2015/08/wasteland.webp-jpg-comparison1.png)

As you see, lossless WebP can achieves half of the JPEG size without visible artifacts (not like JPEG, especially on such scenes triggering JPEG artifacts the crazy way). In fact, to only notice the errors in those WebP you have to compare against PNG (mainly some pixels not having the exact color as expected, you'll notice some blue stars not being as blue as expected), unlike JPEG you can't notice those errors without knowing the original and comparing side to side. PNG is almost 8 time heavier than that lossy WebP and JPEG is not an option, that's a waste.

The other need for WebP are the lightmaps. Those are required to be lossless, well we can afford lossy if artifacts are not noticeable but JPEG is not an option. PNG is really inefficient that's why lossless WebP is a huge win. I don't remember the numbers but PNG can't compete against lossless WebP.

Also PNG is slow, super slow.

PNG is a bad format, a really bad format, a painful format. First it's not efficient. There is nothing purposed for Images in PNG compression. PNG is just a custom container for the usual zlib/zip compression. What makes PNG special for images is that it provides many combinations of various storage variant, like this or that variant of paleted colors or RGB or this or that variant of grayscale, 8-bit or 1-bit alpha channel… PNG “efficiency” does not come from the compression algorithm neither any picture-specific knowledge but from the ability for an optimizer to pick the best storage technique for a given file. That's all. That means most of tools producing PNG just output RGBA PNG (that can't be better than a TGA in a zip) without leveraging optimized preset.

Outside of this, when you have to store RGB or RGBA images, even a plain TGA in a zip would compress as well (by zip itself) as a PNG because PNG is just a TGA compressed with zip using a custom container, and zip compress per file, not globally to the archive so in the end PNG in ZIP is a zip russian doll, a zip in a zip, so you add slowness to slowness.

PNG is painful to deal with because of all those variants made to be combined up to a large amount of usually untested combinations. While fixing PNG transparency in NetRadiant I understood why at the time Internet Developers gave up on fully supporting PNG (and left transparency unfinished) in IE6, I even felt compassion for them.

PNG is so bad I crafted [a special testbed for it](https://github.com/UnvanquishedAssets/UnvanquishedTestAssets/tree/master/src/map-test-pngalpha_src.dpkdir/textures/test-pngalpha_custom_src) so we can check support for it (see [netradiant!102](https://gitlab.com/xonotic/netradiant/-/merge_requests/102) and [netradiant!158](https://gitlab.com/xonotic/netradiant/-/merge_requests/158) and spot issues and track regressions in all the toolchain: level editor, compiler and renderer. PNG is so bad that when converting from PNG to CRN in Urcheon I first convert PNG to TGA to prevent `crunch` to fail on uncommon combination.

WebP is well supported today, major browsers like Chrome and Firefox reads it natively. Image viewers like [XnView MP](https://www.xnview.com/en/xnviewmp/) makes anyone running Linux, Windows and macOS able to browse and watch WebP files while on Linux and other free operating system many tools support it. Picture editors like GIMP running on Linux, Windows, macOS and others allow anyone to open, edit and save WebP images.

While dealing with JPEG I also faced super weird bugs where some images [get sometime reversed upside down given the destination format](https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1838860).

To make sure Urcheon workarounds all the JPG and PNG bugs experienced in the various tools involved, Urcheon converts any image to PNG then from PNG to TGA then from TGA to CRN. That's crazy, but it's required. A game the size of Unvanquished is enough to uncover those wild bugs.

In fact, WebP could be a good option for asset repository because it's far more efficient than PNG as a lossless compressor, takes less place in storage, and compresses far better than PNG. At the time I crafted our repositories GIMP did not support WebP yet. But for a game started today, it would be a better idea to go with WebP in repositories. To optimize our repositories I processed our whole texture set with various PNG optimizers and in the end I bruteforced all of the resulted files with a crazy zopfli compression loop. To get the best of that inefficient PNG compression on our whole corpus my computer spent _days_ doing the computations at 100% CPU usage with performance profile. In dollars the PNG cost would be thousands time more than the WebP cost.

On the contrary lossless WebP saves far more space and processes everything in minutes. And lossy WebP produces very small files with far better quality than JPEG.

So, about the distributed game itself, in the end we ship lossy WebP for skyboxes and lossless WebP for lightmaps. Those two usages are enough to keep WebP. PNG, CRN, and JPEG are not viable alternatives. From all the non-PNG, non-JPEG new fancy formats outside, WebP is the best supported one, at a point that even if being confidential it can be used in repositories because everyone can browse, view them and edit them with both pro, free and quality tools. It takes a lot of time to take off but now WebP is production ready and community ready.
