### ISSUE TITLE
"Void effect" on Vega doors

### ISSUE THREAD

**Issue by slipher** [DaemonEngine/Daemon#205]
The map version I have is `map-vega_1.4.dpk`.

![unvanquished-vegadoorvoid2](https://user-images.githubusercontent.com/7809431/56573142-4f729880-6575-11e9-8463-962528aaa522.png)
![unvanquished-vegadoorvoid3](https://user-images.githubusercontent.com/7809431/56573155-526d8900-6575-11e9-8b34-8c947ae5d092.png)

**Comment by illwieckz** [comment]
it may be an engine issue or a map issue or both:
https://github.com/UnvanquishedAssets/map-vega_src.dpkdir/issues/1

**Comment by illwieckz** [comment]
and it's not only on doors, it's possible to reproduce the issue on other walls from specific point of view, and it's always related to the vis brushes.

**Comment by bmorel** [comment]
Is that still true? Are there commands to reproduce it?

**Comment by illwieckz** [comment]
Related asset issue is marked as fixed:

- https://github.com/UnvanquishedAssets/map-vega_src.dpkdir/issues/1

I forgot it has a duplicate there. This was fixed by modifying some hint brushes.

It's possible there is a bug in the map compiler (q3map2), in the renderer (dæmon), and/or the way it was done was calling for troubles anyway. We don't know.
