### ISSUE TITLE
mark deprecated things with ` [[deprecated]]`

### ISSUE THREAD

**Issue by bmorel** [DaemonEngine/Daemon#583]
And for stuff to deprecate in future times, do something along the lines of:

```
#if VER_MAJOR == 0 && VER_MINOR <= 53
#define DEPRECATED( version ) [[deprecated]]
#else
#define DEPRECATED( version )
#endif
```

**Comment by slipher** [comment]
I don't think deprecated annotations are useful unless the maintainers of the deprecated function and its users are different groups of people.

If we have a deprecation warning and it is treated as an error, then we are forced to immediately migrate everything, so the function could just be deleted instead of deprecated. If we have a deprecation warning and it is not treated as an error, then we have a lot of warning spam which makes it hard to see other useful warnings.

**Comment by necessarily-equal** [comment]
I think this is the kind of stuff that we may not want to care about before daemon gets several games running on it and we need some form of ABI.

This sounds like it would be a waste of resources at the moment. Definitely not a large waste of resources though, but I fail to see the point

**Comment by slipher** [comment]
Warnings that aren't included in the CI's -Werror are generally harmful to developer productivity. By producing a lot of terminal output, they make it harder to see the warnings from *newly written* code which are far more important than ones from existing code. Because the new warnings are more likely to indicate actual bugs, and because some of the new ones may be ones that we have in the CI, meaning the developer is required to fix them before merging the code.

**Comment by bmorel** [comment]
Agree.
