### ISSUE TITLE
The DNS resolver may uncontrollably flood daemon.log

### ISSUE THREAD

**Issue by cu-kai** [DaemonEngine/Daemon#758]
I have discovered this morning that my daemon.log is some 36G after seemingly failing to resolve the master server overnight.

While I have not been able to analyse the 36G daemon.log because I had to restore a backup of my VPS I surmise that it was caused by this as the stdout was flooded with the following message:

`Failed to resolve hostname`

before daemonded finally died with:

`terminate called after throwing an instance of 'std::system_error' what():  No space left on device` after my VPS's virtual disk was filled completely.

Please can this be investigated as a matter of urgency - either stop the spam (and enabling `logs.suppression.enabled` is not the answer because this breaks other things on the server console) or prevent it from logging this garbage to the disk (not really the answer either, because some server owner may run this as a systemd daemon, which means it would just flood the journal anyway).

**Comment by slipher** [comment]
I don't know how to reproduce. Share your server configuration files?

Do you build daemon with any custom patches?

**Comment by cu-kai** [comment]
No custom configuration here aside from `logs.suppression.enabled` set to 0; it looks like it lost connection to the master server and flooded the log. At the same time, issues were reported with the master server on IRC.

**Comment by cu-kai** [comment]
I do, but I don't believe they're relevant to this problem in particular. My cvars are all gameplay related (`g_*`) aside from setting the sv_maxclients, download settings and hostname.

**Comment by slipher** [comment]
Looks like this one is also caused by time wrapping. The resolver is written with the assumption that `Sys::Milliseconds()` will never overflow but it does with the same period as `svs.time`. Due to implementation details, the time overflow can cause a dummy DNS query with the empty string as the hostname to be looked up triggering the `Failed to resolve hostname %s` message.

I'll look into making `Sys::Milliseconds` 64-bit, but it's unlikely I'll find all time overflow related bugs, so your best bet is to configure your server to restart at least once every 24 days.

**Comment by slipher** [comment]
> it does with the same period as `svs.time`

I should say, this is not quite accurate. The svs.time overflow prevention code triggers after 21.7 days of uptime, but `Sys::Milliseconds` only overflows after 24.6 days. So you have a three-day period of your server being dead to the master server and then you only get log spammed by the resolver if you still didn't restart it by then :stuck_out_tongue:

Maybe we should change that svs.time restart code to just kill the server instead of trying to restart the map...

**Comment by necessarily-equal** [comment]
I'm thinking the problem where log file size are unbounded is a more generic one though. I'm not sure this is a good idea to allow the gamelogic to fill up the hard drive if it decides.

I remember @bmorel was symlinking the daemon log files to /dev/null because he had a similar problem. So I'm tempted to reopen.

**Comment by slipher** [comment]
Make a new issue, don't recycle this one

**Comment by bmorel** [comment]
> I remember @bmorel was symlinking the daemon log files to /dev/null because he had a similar problem. So I'm tempted to reopen.

I did not had the problem of disk being full, but I did noticed that shitload of logs are kept around for nothing, and symlinked that folder to /dev/null, because this data can also be gathered through stderr and have no value to me.
This problem is not related to this issue though, as it's expected behavior, where this ticket is about a bug.
