### ISSUE TITLE
Missing candle flame/fire in Metro map

### ISSUE THREAD

**Issue by illwieckz** [DaemonEngine/Daemon#997]
Extracted from this issue that described two bugs:

- https://github.com/DaemonEngine/Daemon/issues/322

This thread is for the missing candle flame/fire sprite effect.

It is believed the bug is related to:

- https://github.com/DaemonEngine/Daemon/issues/730

**Comment by illwieckz** [comment]
Missing flame:

![unvanquished_2023-12-15_024400_000](https://github.com/DaemonEngine/Daemon/assets/2311649/775efd3e-ac2d-4a71-a852-970e0adf406c)

![unvanquished_2023-12-15_024822_000](https://github.com/DaemonEngine/Daemon/assets/2311649/405e17d5-7faf-4afd-b662-5dceb2521e6c)

![unvanquished_2023-12-15_024852_000](https://github.com/DaemonEngine/Daemon/assets/2311649/480660df-c484-4a46-828b-10a181abde4f)

![unvanquished_2023-12-15_024903_000](https://github.com/DaemonEngine/Daemon/assets/2311649/467e5beb-05a7-42f8-9f21-3b27215dbc68)

![unvanquished_2023-12-15_024947_000](https://github.com/DaemonEngine/Daemon/assets/2311649/34442816-2f47-48fd-ab5b-4e209347db2a)

**Comment by slipher** [comment]
I have work in progress for nuking the GLSL-based autosprite implementation as described in https://github.com/DaemonEngine/Daemon/issues/1246#issuecomment-2302015811. I guess the flames must all be rendered with the `lightMapping` shader because that's the part that didn't work with autosprites. Now they show up.

![unvanquished_2024-09-04_004103_000](https://github.com/user-attachments/assets/2dd9c96e-3fc9-46a5-b575-6f0d2cf351ce)
![unvanquished_2024-09-04_004235_000](https://github.com/user-attachments/assets/a77389e0-ad16-4d8a-9b40-2e74498515b6)

**Comment by illwieckz** [comment]
Excellent!

**Comment by slipher** [comment]
> I guess the flames must all be rendered with the `lightMapping` shader because that's the part that didn't work with autosprites.

Actually I think those specifically were broken because they are not opaque. The depth fade code intended for soft particles (unwantedly) runs for all sprites, including BSP ones. For opaque surfaces, alpha is ignored so the depth fade has no effect. For autosprite2 surfaces, the depth fade code gets run with a negative depth value which results in undefined output from the GLSL `smoothstep` function. So transparent autosprite2 surfaces don't show up.

**Comment by illwieckz** [comment]
Fixed by #1281:

- https://github.com/DaemonEngine/Daemon/pull/1281
